[package]
name = "slint-rodio-player"
version = "0.1.2"
edition = "2024"

[dependencies]
audiotags = "0.5.0"
glob = "0.3.3"
rand = "0.9.2"
rodio = "0.21.1"
slint = { version = "1.13.1", features = ["renderer-skia"] }

[build-dependencies]
slint-build = { version = "1.13.1" }

[dev-dependencies]
sysinfo = "0.37.0"
