import {
    ListView,
    ComboBox,
    Slider,
    LineEdit,
    Switch,
    Palette,
} from "std-widgets.slint";
import { ControlPanel } from "control_panel.slint";
import { Sidebar } from "sidebar.slint";
import { SpectrumView } from "spectrum.slint";
import { LyricsPanel } from "lyrics_panel.slint";
import { SongItem, SongListView } from "song_list.slint";
import { TitleBar } from "title_bar.slint";
import { SettingsPanel } from "settings_panel.slint";
import {
    PlayMode,
    LyricItem,
    SongInfo,
    SortKey,
    TriggerSource,
} from "types.slint";

export {
    PlayMode,
    LyricItem,
    SongInfo,
    SortKey,
    TriggerSource,
}

// ui state
export global UIState {
    in-out property <float> progress;
    in-out property <float> duration;
    in-out property <bool> paused;
    in-out property <bool> dragging;
    in-out property <[SongInfo]> song_list;
    in-out property <SongInfo> current_song;
    in-out property <PlayMode> play_mode;
    in-out property <bool> user_listening;
    in-out property <[LyricItem]> lyrics;
    in property <length> lyric_viewport_y;
    in-out property <length> lyric_line_height: 40px;
    in-out property <string> song_dir;
    in property <string> about_info;
    in property <image> album_image;
    in property <[SongInfo]> play_history;
    in property <int> history_index: 0;
    in-out property <SortKey> sort_key;
    in-out property <SortKey> last_sort_key;
    in-out property <bool> sort_ascending: true;
    in-out property <string> lang;
    in-out property <bool> light_ui;
    in-out property <bool> follow_system_theme;
    in property <float> volume;
    in-out property <[float]> spectrum;
    in-out property <bool> show_spectrum: true;
    in-out property <string> app-font-family;
}

export component MainWindow inherits Window {
    default-font-family <=> UIState.app-font-family;
    default-font-size: 14px;
    preferred-width: 850px;
    preferred-height: 500px;
    min-width: 850px;
    min-height: 500px;
    title: "Zeedle";
    icon: @image-url("cover.svg");
    no-frame: true;
    resize-border-width: 5px;
    background: transparent;
    forward-focus: key-input-handler;
    callback toggle_play();
    callback play(SongInfo, TriggerSource);
    callback play_next();
    callback play_prev();
    callback change_progress(float);
    callback switch_mode(PlayMode);
    callback refresh_song_list(string);
    callback sort_song_list(SortKey, bool);
    callback set_lang(string);
    callback change_volume(float);
    callback set_show_spectrum(bool);
    callback set_follow_system_theme(bool);
    callback select_song_dir();
    pure callback format_duration(float) -> string;
    callback window_minimize();
    callback window_maximize();
    callback window_close();
    callback window_drag_delta(float, float);
    in-out property <int> current_page: 0;
    in-out property <bool> sidebar_expanded: false;
    public function set_light_theme(yes: bool) {
        UIState.light_ui = yes;
        if (yes) {
            Palette.color-scheme = ColorScheme.light;
        } else {
            Palette.color-scheme = ColorScheme.dark;
        }
    }

    window-frame := Rectangle {
        width: 100%;
        height: 100%;
        border-radius: root.maximized ? 0px : 6px;
        border-width: root.maximized ? 0px : 1px;
        border-color: Palette.foreground.with_alpha(0.12);

        window-container := Rectangle {
            border-radius: root.maximized ? 0px : 6px;
            clip: true;
            background: Palette.background;

            title-bar := TitleBar {
                y: 0;
                width: 100%;
                is_light_theme <=> UIState.light_ui;
                theme_toggle_enabled: !UIState.follow_system_theme;
                close => { root.window_close(); }
                minimize => { root.window_minimize(); }
                maximize => { root.window_maximize(); }
                toggle_theme => {
                    UIState.follow_system_theme = false;
                    root.set_light_theme(!UIState.light_ui);
                }
                drag_delta(dx, dy) => {
                    root.window_drag_delta(dx, dy);
                }
            }

            HorizontalLayout {
                y: title-bar.height;
                height: root.height - title-bar.height;
                spacing: 0px;

                sidebar := Sidebar {
                    expanded <=> root.sidebar_expanded;
                    current_page: root.current_page;
                    change_page(p) => {
                        root.current_page = p;
                    }
                    request_focus => {
                        root.focus();
                    }
                }

                content-pane := Rectangle {
                    horizontal-stretch: 1;
                    height: 100%;

                    if root.current_page == 0: VerticalLayout {
                        width: 100%;
                        height: 100%;
                        SongListView {
                            ascending <=> UIState.sort_ascending;
                            sort-key <=> UIState.sort_key;
                            last-sort-key <=> UIState.last_sort_key;
                            song-list <=> UIState.song_list;
                            current-song <=> UIState.current_song;
                            sort-songs(key, asc) => {
                                root.sort_song_list(key, asc);
                            }
                            play-song(info, src) => {
                                root.play(info, src);
                            }
                        }

                        ControlPanel {
                            max-height: 80px;
                            min-height: 50px;
                            preferred-height: 60px;
                            progress <=> UIState.progress;
                            duration <=> UIState.duration;
                            paused <=> UIState.paused;
                            dragging <=> UIState.dragging;
                            play_mode <=> UIState.play_mode;
                            current_song <=> UIState.current_song;
                            album_image <=> UIState.album_image;
                            volume <=> UIState.volume;
                            change-progress(p) => {
                                root.change_progress(p);
                                root.focus();
                            }
                            toggle-play() => {
                                root.toggle_play();
                            }
                            play-next() => {
                                root.play_next();
                            }
                            play-prev() => {
                                root.play_prev();
                            }
                            switch-mode(m) => {
                                root.switch_mode(m);
                            }
                            change-volume(v) => {
                                root.change_volume(v);
                                root.focus();
                            }
                            double-clicked() => {
                                root.current_page = 1;
                            }
                            format-duration(d) => {
                                return root.format_duration(d);
                            }
                        }
                    }

                    if root.current_page == 1: Rectangle {
                        width: 100%;
                        height: 100%;
                        z: -5;
                        TouchArea {
                            double-clicked => {
                                root.current_page = 0;
                            }
                        }

                        LyricsPanel {
                            width: 100%;
                            height: 100%;
                            album_image <=> UIState.album_image;
                            current_song <=> UIState.current_song;
                            lyrics <=> UIState.lyrics;
                            progress <=> UIState.progress;
                            lyric_viewport_y <=> UIState.lyric_viewport_y;
                        }
                    }

                    if root.current_page == 2: Rectangle {
                        width: 100%;
                        height: 100%;
                        TouchArea {
                            clicked => {
                                root.focus();
                            }
                        }

                        SettingsPanel {
                            width: 100%;
                            height: 100%;
                            song_dir <=> UIState.song_dir;
                            lang <=> UIState.lang;
                            follow_system_theme <=> UIState.follow_system_theme;
                            show_spectrum <=> UIState.show_spectrum;
                            refresh_song_list(p) => {
                                root.refresh_song_list(p);
                            }
                            set_lang(l) => {
                                root.set_lang(l);
                            }
                            set_follow_system_theme(yes) => {
                                root.set_follow_system_theme(yes);
                            }
                            set_show_spectrum(yes) => {
                                root.set_show_spectrum(yes);
                            }
                            select_song_dir => {
                                root.select_song_dir();
                            }
                        }
                    }

                    if root.current_page == 3: VerticalLayout {
                        width: 100%;
                        height: 100%;
                        alignment: center;
                        spacing: 10px;
                        HorizontalLayout {
                            alignment: center;
                            Image {
                                source: @image-url("cover.svg");
                                width: 120px;
                                height: 120px;
                            }
                        }

                        Text {
                            text: UIState.about_info;
                            horizontal-alignment: center;
                        }
                    }
                }
            }

            spectrum-bg := Rectangle {
                x: root.sidebar_expanded ? 210px : 60px;
                width: root.width - self.x;
                y: title-bar.height;
                height: root.height - title-bar.height;
                z: -5;
                visible: UIState.show_spectrum;
                SpectrumView {
                    width: parent.width;
                    height: 60px;
                    y: parent.height - self.height;
                    bins: UIState.spectrum;
                }
            }

            key-input-handler := FocusScope {
                focus-on-click: false;
                key-released(event) => {
                    if event.text == Key.Space {
                        root.toggle_play();
                        return accept;
                    } else if event.text == Key.RightArrow || event.text == Key.DownArrow {
                        root.play_next();
                        return accept;
                    } else if event.text == Key.LeftArrow || event.text == Key.UpArrow {
                        root.play_prev();
                        return accept;
                    } else if event.text == Key.F1 {
                        root.current_page = 0;
                        return accept;
                    } else if event.text == Key.F2 {
                        root.current_page = 1;
                        return accept;
                    } else if event.text == Key.F3 {
                        root.current_page = 2;
                        return accept;
                    } else if event.text == Key.F4 {
                        root.current_page = 3;
                        return accept;
                    }
                    return reject;
                }
            }
        }
    }
}
