import { Palette } from "std-widgets.slint";
export component LyricLine inherits Rectangle {
    height: 40px;
    in-out property <string> content;
    in-out property <bool> playing;
    callback triggered();
    Text {
        width: 100%;
        horizontal-alignment: center;
        vertical-alignment: center;
        color: playing ? Palette.accent-background : Palette.foreground;
        text: content;
        font-size: playing ? 20px : 17px;
        overflow: TextOverflow.elide;
    }

    background: transparent;
}
