import { Theme } from "theme.slint";
import { ListView } from "std-widgets.slint";
import { SongInfo, LyricItem } from "types.slint";

export component LyricLine inherits Rectangle {
    height: 40px;
    background: area.has-hover ? Theme.song-hover : transparent;
    border-radius: 5px;
    in-out property <string> content;
    in-out property <bool> playing;
    area := TouchArea { }

    Text {
        width: 100%;
        horizontal-alignment: center;
        vertical-alignment: center;
        color: playing ? Theme.accent : Theme.text;
        text: content;
        font-size: playing ? 20px : 17px;
        overflow: TextOverflow.elide;
        Tooltip {
            VerticalLayout {
                padding: 5px;
                Text {
                    text: content;
                }
            }
        }
    }
}

export component LyricsPanel inherits Rectangle {
    in property <image> album_image;
    in property <SongInfo> current_song;
    in property <[LyricItem]> lyrics;
    in property <float> progress;
    in-out property <length> lyric_viewport_y;
    background: Theme.surface;
    HorizontalLayout {
        width: 100%;
        height: 100%;
        VerticalLayout {
            width: lyrics.length != 0 ? 30% : 100%;
            alignment: center;
            lyric-image := Rectangle {
                x: parent.width / 2 - self.width / 2;
                width: root.height * 0.40;
                height: self.width;
                clip: true;
                border-radius: 8px;
                drop-shadow-blur: 8px;
                Image {
                    width: 100%;
                    height: 100%;
                    source: album_image;
                }
            }

            Text {
                states [
                    has-lyrics when lyrics.length != 0: {
                        x: lyric-image.x;
                    }
                    no-lyrics when lyrics.length == 0: {
                        horizontal-alignment: center;
                    }
                ]

                width: 100%;
                height: 25px;

                vertical-alignment: bottom;
                text: @tr("Artist: {}", current_song.singer);
                overflow: elide;
            }

            Text {
                states [
                    has-lyrics when lyrics.length != 0: {
                        x: lyric-image.x;
                    }
                    no-lyrics when lyrics.length == 0: {
                        horizontal-alignment: center;
                    }
                ]

                width: 100%;
                height: 25px;

                vertical-alignment: bottom;
                text: @tr("Title: {}", current_song.song_name);
                overflow: elide;
            }
        }

        VerticalLayout {
            width: lyrics.length != 0 ? 70% : 0%;
            alignment: center;
            ListView {
                height: 100%;
                width: 100%;
                mouse-drag-pan-enabled: false;
                viewport-y <=> root.lyric_viewport_y;
                for item in root.lyrics: LyricLine {
                    content: item.text;
                    playing: (root.progress >= item.time) && (root.progress < item.time + item.duration);
                }
            }
        }
    }
}
