import {
    ComboBox,
    LineEdit,
    Switch,
} from "std-widgets.slint";

export component SettingsPanel inherits Rectangle {
    in-out property <string> song_dir;
    in-out property <string> lang;
    in-out property <bool> light_ui;
    in-out property <bool> show_spectrum;
    callback refresh_song_list(string);
    callback set_lang(string);
    callback set_light_theme(bool);
    callback set_show_spectrum(bool);
    VerticalLayout {
        width: 100%;
        height: 100%;
        alignment: center;
        spacing: 20px;
        HorizontalLayout {
            alignment: center;
            spacing: 10px;
            Rectangle {
                height: 30px;
                width: 200px;
                Text {
                    x: parent.width - self.width;
                    vertical-alignment: center;
                    text: @tr("Music directory: ");
                }
            }

            LineEdit {
                width: 200px;
                text <=> song_dir;
                accepted(p) => {
                    refresh_song_list(p);
                }
            }
        }

        HorizontalLayout {
            alignment: center;
            spacing: 10px;
            Rectangle {
                height: 30px;
                width: 200px;
                Text {
                    x: parent.width - self.width;
                    vertical-alignment: center;
                    text: @tr("Language: ");
                }
            }

            ComboBox {
                width: 200px;
                current-value <=> lang;
                model: ["", "zh_CN", "es", "fr", "de", "ru"];
                selected(current-value) => {
                    root.set_lang(current-value);
                }
            }
        }

        HorizontalLayout {
            alignment: center;
            spacing: 10px;
            Rectangle {
                height: 30px;
                width: 200px;
                Text {
                    x: parent.width - self.width;
                    vertical-alignment: center;
                    text: @tr("Light theme: ");
                }
            }

            Switch {
                width: 200px;
                checked <=> light_ui;
                text: self.checked ? @tr("On") : @tr("Off");
                toggled => {
                    root.set_light_theme(self.checked);
                }
            }
        }

        HorizontalLayout {
            alignment: center;
            spacing: 10px;
            Rectangle {
                height: 30px;
                width: 200px;
                Text {
                    x: parent.width - self.width;
                    vertical-alignment: center;
                    text: @tr("Spectrum display: ");
                }
            }

            Switch {
                width: 200px;
                checked <=> show_spectrum;
                text: self.checked ? @tr("On") : @tr("Off");
                toggled => {
                    root.set_show_spectrum(self.checked);
                }
            }
        }
    }
}