import { Theme } from "theme.slint";
import { ListView, VerticalBox } from "std-widgets.slint";
import { TriggerSource, SongInfo, SortKey } from "types.slint";

component SortIcon inherits Rectangle {
    in-out property <bool> ascending: true;
    in-out property <bool> display: true;
    height: 15px;
    width: 15px;
    background: transparent;
    if !ascending && display: Path {
        commands: "M 5 1 L 5 9 L 7 7";
        stroke: Theme.text-tertiary;
        stroke-width: 1px;
    }
    if ascending && display: Path {
        commands: "M 5 9 L 5 1 L 3 3";
        stroke: Theme.text-tertiary;
        stroke-width: 1px;
    }
}

component TitleBarItem inherits Rectangle {
    in property <string> name:"name";
    in-out property <bool> display-sort-icon <=> arrow.display;
    in-out property <bool> ascending-sort <=> arrow.ascending;
    Rectangle {
        width: 100%;
        height: 100%;
        text := Text {
            text: name;
            color: Theme.text-tertiary;
            x: parent.width * 0.4;
            y: parent.height / 2 - self.height / 2;
        }

        arrow := SortIcon {
            ascending: true;
            width: 12px;
            height: 12px;
            x: text.x + text.width + 5px;
            y: parent.height / 2 - self.height / 2;
        }
    }
}

component SortColumn inherits Rectangle {
    in property <string> label;
    in property <SortKey> sort-key;
    in property <SortKey> current-key;
    in property <bool> ascending;
    callback clicked(SortKey, bool);
    height: 100%;
    width: 33%;

    touch-area := TouchArea {
        clicked => {
            root.clicked(root.sort-key, root.ascending);
        }
        TitleBarItem {
            width: 100%;
            height: 100%;
            name: root.label;
            background: touch-area.has-hover ? Theme.hover : transparent;
            display-sort-icon: root.current-key == root.sort-key;
            ascending-sort: root.ascending;
        }
    }
}

component SortBar inherits Rectangle {
    height: 30px;
    in-out property <SortKey> key;
    in-out property <bool> ascending;
    callback sort-items(SortKey, bool);
    background: Theme.surface;

    HorizontalLayout {
        alignment: space-between;
        SortColumn {
            label: @tr("Title");
            sort-key: SortKey.BySongName;
            current-key: root.key;
            ascending: root.ascending;
            clicked(key, asc) => {
                root.sort-items(key, asc);
            }
        }

        SortColumn {
            label: @tr("Artist");
            sort-key: SortKey.BySinger;
            current-key: root.key;
            ascending: root.ascending;
            clicked(key, asc) => {
                root.sort-items(key, asc);
            }
        }

        SortColumn {
            label: @tr("Duration");
            sort-key: SortKey.ByDuration;
            current-key: root.key;
            ascending: root.ascending;
            clicked(key, asc) => {
                root.sort-items(key, asc);
            }
        }
    }
}

export component SongItem inherits Rectangle {
    height: 30px;
    in property <SongInfo> info:{ id:0, song_name:"xxx", singer:"xxx", duration:"xxx", song_path:"xxx" };
    in property <bool> playing:false;
    callback double_clicked();
    background: playing ? Theme.hover : (area.has-hover ? Theme.song-hover : Theme.surface);
    VerticalLayout {
        area := TouchArea {
            double-clicked => {
                double_clicked();
            }
            HorizontalLayout {
                alignment: space-between;
                Rectangle {
                    width: 33%;
                    Text {
                        width: 100%;
                        x: parent.width * 0.4;
                        text: info.song-name;
                        font-weight: root.playing ? 600 : 400;
                        color: root.playing ? Theme.accent : Theme.text;
                        overflow: elide;
                    }
                }

                Rectangle {
                    width: 33%;
                    Text {
                        width: 100%;
                        x: parent.width * 0.4;
                        text: info.singer;
                        color: root.playing ? Theme.accent : Theme.text;
                        overflow: elide;
                    }
                }

                Rectangle {
                    width: 33%;
                    Text {
                        x: parent.width * 0.4;
                        text: info.duration;
                        color: root.playing ? Theme.accent : Theme.text;
                    }
                }
            }

            Tooltip {
                Rectangle {
                    border-color: Theme.text;
                    VerticalLayout {
                        padding: 5px;
                        Text {
                            text: @tr("Title: {}\nArtist: {}\nDuration: {}", info.song-name, info.singer, info.duration);
                        }
                    }
                }
            }
        }
    }
}

export component SongListView inherits Rectangle {
    in-out property <bool> ascending;
    in-out property <SortKey> sort-key;
    in-out property <SortKey> last-sort-key;
    in-out property <[SongInfo]> song-list;
    in property <SongInfo> current-song;
    callback sort-songs(SortKey, bool);
    callback play-song(SongInfo, TriggerSource);
    background: Theme.surface;
    VerticalLayout {
        width: 100%;
        height: 100%;
        SortBar {
            ascending: root.ascending;
            key: root.sort-key;
            sort-items(key, ascending) => {
                if (root.last-sort-key == key) {
                    root.sort-songs(key, !ascending);
                } else {
                    root.sort-songs(key, true)
                }
            }
        }

        ListView {
            for item in root.song-list: SongItem {
                info: item;
                playing: item.song-path == root.current-song.song-path;
                double_clicked => {
                    root.play-song(item, TriggerSource.ClickItem);
                }
            }
        }
    }
}
