import { ListView } from "std-widgets.slint";
import { SongInfo, TitleBar, SongItem, SortKey } from "song.slint";
import { TriggerSource } from "trigger.slint";

export component SongListView inherits Rectangle {
    in-out property <bool> ascending;
    in-out property <SortKey> sort-key;
    in-out property <SortKey> last-sort-key;
    in-out property <[SongInfo]> song-list;
    in property <SongInfo> current-song;
    callback sort-songs(SortKey, bool);
    callback play-song(SongInfo, TriggerSource);
    VerticalLayout {
        width: 100%;
        height: 100%;
        TitleBar {
            ascending: root.ascending;
            key: root.sort-key;
            sort-items(key, ascending) => {
                if (root.last-sort-key == key) {
                    root.sort-songs(key, !ascending);
                } else {
                    root.sort-songs(key, true)
                }
            }
        }

        ListView {
            for item in root.song-list: SongItem {
                info: item;
                playing: item.song-path == root.current-song.song-path;
                double_clicked => {
                    root.play-song(item, TriggerSource.ClickItem);
                }
            }
        }
    }
}
